# Project: Lab11
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Lab11.o functionLab11.o
LINKOBJ  = Lab11.o functionLab11.o
LIBS     = -L"D:/Програма/Dev-Cpp/MinGW64/lib" -L"D:/Програма/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Програма/Dev-Cpp/MinGW64/include" -I"D:/Програма/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Програма/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Програма/Dev-Cpp/MinGW64/include" -I"D:/Програма/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Програма/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Програма/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Lab11.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Lab11.o: Lab11.c
	$(CC) -c Lab11.c -o Lab11.o $(CFLAGS)

functionLab11.o: functionLab11.c
	$(CC) -c functionLab11.c -o functionLab11.o $(CFLAGS)
