# Project: Lab12
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Lab12.o
LINKOBJ  = Lab12.o
LIBS     = -L"D:/Програма/Dev-Cpp/MinGW64/lib" -L"D:/Програма/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Програма/Dev-Cpp/MinGW64/include" -I"D:/Програма/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Програма/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Програма/Dev-Cpp/MinGW64/include" -I"D:/Програма/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Програма/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Програма/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Lab12.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Lab12.o: Lab12.c
	$(CC) -c Lab12.c -o Lab12.o $(CFLAGS)
